# Generated by Django 6.0.5 on 2026-05-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='purchase_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
