# Generated by Django 6.0.5 on 2026-05-12 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0002_couple_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouplePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='couple_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='couples.couple')),
            ],
        ),
    ]
