# Generated by Django 6.0.5 on 2026-05-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0003_couplephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='pix_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
