# Generated by Django 6.0.5 on 2026-05-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0004_couple_pix_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='pix_qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='pix_qrcodes/'),
        ),
    ]
